"use client";

/* eslint-disable @next/next/no-img-element -- external GitHub SVG widgets */

import { socialLinks } from "@/lib/data";
import AnimatedSection from "./AnimatedSection";
import LazyGitHubContributionHeatmap from "./LazyGitHubContributionHeatmap";
import SectionHeading from "./SectionHeading";

const THEME = "merko";

/** Default branch for github.com/{user}/{user} profile repo (matches grs.yml push target). */
const PROFILE_REPO_BRANCH = "main";

/** SVGs generated by .github/workflows/grs.yml in the profile repo (token-backed, daily). */
function githubProfileReadmeSvg(
  user: string,
  file: "stats" | "top-langs",
): string {
  return `https://raw.githubusercontent.com/${user}/${user}/${PROFILE_REPO_BRANCH}/profile/${file}.svg`;
}

function githubUsernameFromProfileUrl(url: string): string {
  try {
    const path = new URL(url).pathname.replace(/^\//, "").replace(/\/$/, "");
    const segment = path.split("/")[0];
    return segment && segment.length > 0 ? segment : "v4irajvimu";
  } catch {
    return "v4irajvimu";
  }
}

export default function CollaborationsSection() {
  const githubUrl =
    socialLinks.find((s) => s.name === "GitHub")?.url ??
    "https://github.com/v4irajvimu";

  const user = githubUsernameFromProfileUrl(githubUrl);

  const statsImg = githubProfileReadmeSvg(user, "stats");
  const topLangsImg = githubProfileReadmeSvg(user, "top-langs");
  const streakImg = `https://github-readme-streak-stats.herokuapp.com?user=${user}&theme=${THEME}`;

  const cardClass =
    "inline-block max-w-full rounded-xl border border-card-border bg-card/50 p-3 transition-colors hover:border-accent/30 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent";

  /** Full-width card so the contribution calendar can span the section. */
  const heatmapCardClass =
    "w-full max-w-full rounded-xl border border-card-border bg-card/50 p-3 md:p-4 transition-colors hover:border-accent/30";

  return (
    <section
      id="collaborations"
      className="relative py-24 px-4 overflow-hidden"
    >
      <div className="mx-auto max-w-6xl relative">
        <AnimatedSection>
          <SectionHeading>
            GitHub <span className="gradient-text">Collaborations</span>
          </SectionHeading>
        </AnimatedSection>

        <AnimatedSection delay={0.1}>
          <p className="mx-auto max-w-2xl text-center text-muted-foreground mb-10">
            GitHub stats and top languages load SVGs from the profile repository
            (refreshed on a schedule by GitHub Actions). The contribution
            calendar and streak use live data.
          </p>
        </AnimatedSection>

        <div className="space-y-8">
          {/* Contribution Calendar */}
          <AnimatedSection delay={0.25}>
            <div className={heatmapCardClass}>
              <LazyGitHubContributionHeatmap username={user} />
              <p className="mt-4 text-center">
                <a
                  href={githubUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs text-muted-foreground hover:text-accent transition-colors"
                >
                  Open full profile on GitHub
                </a>
              </p>
            </div>
          </AnimatedSection>
          {/* Streak */}
          <AnimatedSection delay={0.2}>
            <a
              href={githubUrl}
              target="_blank"
              rel="noopener noreferrer"
              className={`${heatmapCardClass} flex justify-center focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent`}
            >
              <img
                src={streakImg}
                alt="GitHub contribution streak: total contributions, current streak, and longest streak"
                width={495}
                height={195}
                loading="lazy"
                decoding="async"
                className="w-full md:w-1/2 max-w-full h-auto rounded-lg shrink-0"
              />
            </a>
          </AnimatedSection>

          {/* Stats and Top Languages */}
          <AnimatedSection delay={0.15}>
            <div className="grid gap-6 md:grid-cols-2 justify-items-center items-center">
              <a
                href={githubUrl}
                target="_blank"
                rel="noopener noreferrer"
                className={cardClass}
              >
                <img
                  src={statsImg}
                  alt={`${user} on GitHub: stars, commits, pull requests, issues, and contributions`}
                  width={495}
                  height={195}
                  loading="lazy"
                  decoding="async"
                  className="max-w-full h-auto rounded-lg"
                />
              </a>
              <a
                href={githubUrl}
                target="_blank"
                rel="noopener noreferrer"
                className={cardClass}
              >
                <img
                  src={topLangsImg}
                  alt={`${user} most-used languages on GitHub`}
                  width={495}
                  height={195}
                  loading="lazy"
                  decoding="async"
                  className="max-w-full h-auto rounded-lg"
                />
              </a>
            </div>
          </AnimatedSection>
        </div>
      </div>
    </section>
  );
}
